### ISSUE TITLE
Several missing information

### ISSUE THREAD

**Issue by mathiaslegrand1** [romainsi/zabbix-VB-R-SQL#23]
hello, 

Following the migration between the old repositories and this one on my windows 2019 server, I have data that is no longer received by the zabbix server.
- The item "total number of veeam backups" is empty.
- The "Veeam Job Info" item is an empty json list.

I don't see where the backup replication information is.

![VEEAM](https://user-images.githubusercontent.com/28758850/179524185-5d34f941-7716-49b0-b4b5-6a898e93e2d0.png)

Can you help me ?

Thanks,
Mathias

**Comment by aholiveira** [comment]
Hello @mathiaslegrand1,
When you imported the template to Zabbix, did you clear the previous items?
Try the following:
- "Unlink and clear" the template from the host
- Reimport the template again, and please check all "Delete missing", except "Template linkage", to make sure the old items are deleted from the template
- Link the template to the host again
- Check if the script on the host has all the correct credentials (lines 73-78)

After this you should be getting all the data correctly again. There were a few incompatible changes between template versions, which require a full "reimport" of the template on Zabbix. New installations are not affected.

Regards

**Comment by aholiveira** [comment]
Hello @mathiaslegrand1,
If you run the script manually you should see the information that should be sent to Zabbix.
Also, make sure that the command does not run for more than 30 seconds. You can use the command below to check the execution time of the script.
`(Measure-Command -Expression{ powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent 2\scripts\zabbix_vbr_job.ps1" "JobsInfo"}).TotalSeconds`

If it takes longer to execute than 30 seconds then you need to ajust the "Timeout" parameter on the agent configuration.
Also, the old items should have been deleted from the host and recreated.
Make sure that the item key format is like veeam.Jobs.xxx['{#JOBTYPE}','{#JOBID}'] (example: veeam.Jobs.Retry['63','4dc863a2-e51b-465c-a473-9f5f5fcb3e68']). If they are not in this format, delete the items directly from the host and wait for them to be recreated when the discovery rule is run again.

Regards.

**Comment by mathiaslegrand1** [comment]
Hello @aholiveira ,

Below is the result of the commands. For the TotalJob argument, it returns nothing. Also, as you can see, the execution time is less than 30 seconds.
![VEEAM3](https://user-images.githubusercontent.com/28758850/179779041-c7d0745f-6393-4562-9d57-48e7b16eb27d.png)

Also, the keys are in the correct format, but the discever doesn't create them.

![image](https://user-images.githubusercontent.com/28758850/179778968-b3533896-fbfb-4436-ad62-08281a86aa88.png)

Thanks.

**Comment by aholiveira** [comment]
Hello,
From the screenshot when you run with "JobsInfo" parameter it is not reading anything.
Either the variables are wrong on the script or the SQL user does not have permissions to read information from Veeam's database.
Also, the second screenshot is from the discovery rule. I was questioning if there were items created on the host, but since "JobsInfo" is not returning anything, then you won't get any items created.
You can add the "-Debug" parameter to the script when running it manually to get some more information, which might help pinpoint the issue.

Regards

**Comment by mathiaslegrand1** [comment]
Hello,

The result of the debug.

![image](https://user-images.githubusercontent.com/28758850/179785125-65f64651-a658-479b-9132-5eec2b15f086.png)


Thanks

**Comment by mathiaslegrand1** [comment]
I did add the "db_datareader" role. I entered the command you gave me under the zabbixveeam session, I can see the data. Also for total jobs, I have the same results.

**Comment by aholiveira** [comment]
So, it is working now, correct?

**Comment by aholiveira** [comment]
Note the following:
 - Only the jobs of types listed in the first line of the debug output are supported ("Job types: ....").
 - Of the supported job types only the jobs which are run automatically are considered (if you run the jobs manually they will not be discovered).

Make sure that your jobs are of the supported types and are run automatically (using a schedule), otherwise they will not be found by the script.
On the last line of the debug output I see "job count: 2", which should mean that you have 2 jobs of supported types but if they're not being discovered then it should mean that they were manually run the last time. Wait for them to run automatically on Veeam and they should come up on Zabbix.

**Comment by aholiveira** [comment]
Replace line 196 of the script from:
`Write-Output $_.Exception.Message`
to
`Write-Debug $_.Exception.Message`

Then run the script again with "-Debug" and "JobsInfo"

**Comment by mathiaslegrand1** [comment]
Hello @aholiveira ,

I can confirm that backup jobs and backup replications are only launched once a day and automatically. Normally nobody to launch backup manually.

For debug it tells me that the script can't connect to the db.
![VEEAM6](https://user-images.githubusercontent.com/28758850/179936195-2bfa1433-a2a9-460b-9345-4a7b067320fb.png)

**Comment by ahumain** [comment]
DB connection works. I'm waiting for the discovery to be sure that everything is ok.

![VEEAM7](https://user-images.githubusercontent.com/28758850/179968556-ca390e8f-8ca0-4b4d-b291-29aee4b4e70e.png)

**Comment by ahumain** [comment]
it's ok @aholiveira 

Thanks for your help
