### ISSUE TITLE
script.ps1 brings empty result

### ISSUE THREAD

**Issue by elvisfalmeida** [romainsi/zabbix-VB-R-SQL#25]
Hi guys, I need some help.

I did every step of the installation, including the version of Veeam running is this: **11.0.1.1261**

But the only parameter that brings information is RepoInfo, the others don't bring results. I took some prints, if anyone can help me I would appreciate it.

![image](https://user-images.githubusercontent.com/21308576/193338121-69bddcc6-af85-4651-b8a1-b1955f81af67.png)

![image](https://user-images.githubusercontent.com/21308576/193338356-3adea66e-031c-4d90-93a4-5491e42845c5.png)

**Comment by aholiveira** [comment]
Hello,
Can you run the script using debug parameter?
`zabbix_vbr_job.ps1 jobsinfo -Debug`
It might help understand the issue.
Check if SQL permissions are correct.

Regards.

**Comment by TarrX** [comment]
The default installation of veeam sets up a database instance, called VEEAMSQL2016 for example. You need to use like localhost\VEEAMSQL2016  in your configuration for the sql server. Also the database instance is configured for windows authentication only. You can change this in the management studio, server properties, security, set to SQL and Windows auth.

**Comment by sascha005** [comment]
Hello, same here. Don't see any Job Data in Zabbix :

![image](https://user-images.githubusercontent.com/47948688/197268360-187efbc8-af35-4b68-ab0c-22cd3e1e1b0d.png)

and with Debug:

![image](https://user-images.githubusercontent.com/47948688/197268597-65491fcc-87b1-4156-ba7c-48dd4f7d410b.png)

Cheers
Sascha

**Comment by elvisfalmeida** [comment]
> Hello, same here. Don't see any Job Data in Zabbix :
> 
> ![image](https://user-images.githubusercontent.com/47948688/197268360-187efbc8-af35-4b68-ab0c-22cd3e1e1b0d.png)
> 
> and with Debug:
> 
> ![image](https://user-images.githubusercontent.com/47948688/197268597-65491fcc-87b1-4156-ba7c-48dd4f7d410b.png)
> 
> Cheers Sascha

**Sorry for the bad English, I'm using Google Translate.**

The problem was in fact the user's permission, so as not to waste too much time, since I have no knowledge of messing with the database, I just adjusted the script to authenticate with the same sql user. 

Authentication based on Windows Credecias, in my case it looked like this:

![image](https://user-images.githubusercontent.com/21308576/197270008-b979f797-562c-4d76-ac48-a756fdce5fa7.png)

**Comment by paddif** [comment]
i've logged in via sql server management Studio and i had to change the following setting on the SQL Server:
Seem's like by Default the SQL Server 2016 doesn't allow SQL Server Based Login.
![image](https://user-images.githubusercontent.com/4719545/203142689-54262ab1-0dce-4573-9ccb-449b557a2a15.png)

How i found out:
I've added the following line to the script:
![image](https://user-images.githubusercontent.com/4719545/203143186-d23d8f05-2559-48af-9d10-cca9ec9eb739.png)
and Got the following error: (Translated to English: 
`DEBUG: Exception when calling "Open" with 0 argument(s): "Login failed for user`
)
![image](https://user-images.githubusercontent.com/4719545/203143249-d854cf86-bfe8-49f1-8033-bf1c0891e344.png)

**Comment by aholiveira** [comment]
Hello,
As per the configuration steps on the package README, check that "zabbixveeam" user has 'db_datareader' role assigned on te database.
You can use management studio to assign this. Assuming you have the user already created, run the following commands:
```sql
USE [VeeamBackup]
EXEC sp_addrolemember 'db_datareader', 'zabbixveeam';
GO
```
You should replace "zabbixveeam" with the correct username (the same configured on the script).
Otherwise, if the user is not yet created, the following commands will create the user and assign the necessary role. Also, replace "CHANGEME" with the correct password (you should create a new, more secure, password for the user.
```sql
USE [VeeamBackup]
CREATE LOGIN [zabbixveeam] WITH PASSWORD = N'CHANGEME', CHECK_POLICY = OFF, CHECK_EXPIRATION = OFF;
CREATE USER [zabbixveeam] FOR LOGIN [zabbixveeam];
EXEC sp_addrolemember 'db_datareader', 'zabbixveeam';
GO
```
In any case, unless the user configured on the script has, at least, 'db_datareader' role assigned on the database (or any other role which allows, at least READ permissions on the Veeam database (usually named "VeeamBackup") it will NOT be able to get any information regarding the jobs. Repository information is available because it is not collected using the database but using WIM.
It is also possible to use "sa" or any other SQL user with the correct. However, by default, the SQL Express instance created by Veeam during installation, will NOT allow access through an SQL user. That has to be enabled as shown on the https://github.com/romainsi/zabbix-VB-R-SQL/issues/25#issuecomment-1322548609 above. We'll update the README to make this more clear.
Hopefully this will help you get the information from Veeam into Zabbix.

Regards.

**Comment by azizbaghirov** [comment]
> The default installation of veeam sets up a database instance, called VEEAMSQL2016 for example. You need to use like localhost\VEEAMSQL2016 in your configuration for the sql server. Also the database instance is configured for windows authentication only. You can change this in the management studio, server properties, security, set to SQL and Windows auth.

this helped me, thanks a lot!!
