### ISSUE TITLE
How to remove "ended with Warning" indicator + close manually an error

### ISSUE THREAD

**Issue by dimaiam** [romainsi/zabbix-VB-R-SQL#28]
Hello!

I want to remove "ended with Warning" indicator from zabbix, What part of the code i have to remove to succed?

And another question: i been doing some tests, and if a backup job just failed how the problem closes? waiting for the new backup?

Thanks you!

**Comment by aholiveira** [comment]
Hello,
Your questions have more to do with general Zabbix way of working than with this template itself.
You can disable any trigger which prevents it from being triggered. Just go to the host configuration, triggers and click on "Enabled" (or open the trigger definition, scroll to the bottom and uncheck "Enabled"). This will disable the trigger.
We could have a macro to "turn off" all or individual triggers (without disabling them) but currently there is none.

The triggers for backup jobs are resolved at the next job execution. If at the end of the job it fails again the trigger will be activated again. You can also modify the trigger to "Allow manual close", which will enable you to manually close the ticket. However, due to the way that the trigger works it will reopen again at the next data reading cycle, so this won't help much in this case. It might be useful in other situations, though.
Hope this helps.

Regards.

**Comment by dimaiam** [comment]
Thank you very much for the response, I have been able to complete everything to my liking. Thank you also for the incredible work that you have done!
