### ISSUE TITLE
Problem with Veeam Repository discovery rule

### ISSUE THREAD

**Issue by dimaiam** [romainsi/zabbix-VB-R-SQL#29]
Hello!

I have this problem with Veeam Repository discovery rule:

![error](https://user-images.githubusercontent.com/88244777/208913662-a43f56df-7be5-4dfd-bd9e-227dae3a3e43.PNG)

it was working fine until yestarday

Thanks you!

**Comment by aholiveira** [comment]
Hello,
That error is apparently due to an authentication error on Veeam's server. You seem to be using a remote connection to Veeam server to get the repository information. Although this is possible you should make sure, in this case, that the WinRM service is properly configured to allow remote connections. However, it is simpler, easier and more secure to run the script directly on Veeam's server, since this way you don't have to open WinRM to external connections.
Also, if everything was running fine until yesterday and today it is not working (and there were no updates to this in between) you should check if there were other changes in your servers or if the user being used for authentication has not been blocked, had it's password changed or some other modification was done, which is preventing the correct operation of the script.

Hope this helps.

Regards.
