### ISSUE TITLE
Is possible to close a trigger witouth disable?

### ISSUE THREAD

**Issue by dimaiam** [romainsi/zabbix-VB-R-SQL#30]
Hello!!

I have enabled the option to manually close a trigger, but after a few seconds the problem reopens. Is there any way to prevent this from happening?

Thanks!

**Comment by aholiveira** [comment]
Hello,
With the current version of this it is not possible to do it.
Also, given the way that this works, manually closing a trigger will not work now or in the foreseeable future (a complete rework of this would be needed).
You can acknowledge the trigger and (if you notifications are configured with that condition), should prevent further notifications about it until the next backup cycle.
I see only two options to "solve" this:
1 - Simply disable the trigger.
2 - Create macro `{$VEEAM_JOB_RESULT_WARN}` with value "1" on the template. Add the following condition to the trigger prototypes: `{$VEEAM_JOB_RESULT_WARN:"{#JOBID}"}=1 and <rest-of-trigger-expression>`. Then, for the jobs that you do not want the trigger to be activated, create the corresponding macro on the host. We can probably incorporate this into a new version of the template, to enable a fine grained trigger control and to use the recommendations from zabbix.

However, both of these "solutions" will result in the trigger never being activated, which might not be exactly what you want.
Right now I do not see any way to allow the trigger to be activated and then close it before the next backup cycle. Can you elaborate more on why this is needed so that we can try to figure out a way to do it?

Regards.
