### ISSUE TITLE
Script don't return values

### ISSUE THREAD

**Issue by marcos-lazaro** [romainsi/zabbix-VB-R-SQL#32]
Hi guys, please help-me!

I performed the entire procedure described in the README, but I am not getting values from TotalJob and JobsInfo. It just returns nothing.
RepoInfo returns the values correctly.

![image](https://user-images.githubusercontent.com/123191214/213751331-9e841ac2-3ed0-47b3-9e56-7ca8e6051224.png)

**Comment by aholiveira** [comment]
Hello,
That is usually due to authentication failures against the SQL Server where the Veeam database is.
Make sure that all the correct permissions are given and that SQL logins are enabled (they are disabled by default). Do not forget that changing the authentication types will require a restart of the service.
Please run the script with the "Debug" parameter and check the output to see where the failure is.

Regards.

**Comment by marcos-lazaro** [comment]
I'm using Windows Authentication mode, my SQL is integrated with AD, in this case I use an AD user to read the database.

In the script I put the DOMAIN/USER and apparently I'm still missing something. The SQL logs show me that the script is trying to login as SQL Authentication.

**Comment by roughneck2k3** [comment]
Hi, 
i have the same problem... i dont get any values. When i run the script with debug enabled, the connection seems to be okay, im able to opening a sql connection but dont get any values... Any idea? I use SQL instead of AD authentication. 

Regards

**Comment by aholiveira** [comment]
> I'm using Windows Authentication mode, my SQL is integrated with AD, in this case I use an AD user to read the database.
> 
> In the script I put the DOMAIN/USER and apparently I'm still missing something. The SQL logs show me that the script is trying to login as SQL Authentication.

Hello. You need to change "SQLIntegratedSecurity" variable to "True" to use integrated authentication. *However*, please note that when Zabbix agent is running the script it will run with "LocalSystem" or "NetworkService" credentials (because it is running as a Windows service on the host) so you will probably need to authorize the computer object (from AD) to access the database.

It is easier to create an SQL user and use those credentials on the script, than to use AD authentication (although it is possible).

Hope this helps.

Regards.

**Comment by marcos-lazaro** [comment]
> 

Hey,
I did it this way. I put the AD user to run the Zabbix agent on the machine, this way he can log in to SQL using the AD credentials.

Thank you for your help.

**Comment by aholiveira** [comment]
> Hi, i have the same problem... i dont get any values. When i run the script with debug enabled, the connection seems to be okay, im able to opening a sql connection but dont get any values... Any idea?
> 
> Regards

Hello.
Is the user allowed to query the database? If you can establish a connection when manually running the script, make sure you are using an SQL user with proper access with the database. Alternatively, if you are using integrated authentication bear in mind that Zabbix agent is running as a Windows service, and will use the computer object account to connect the database, not your user.

The README shows the exact requirements needed for proper access to the Veeam database, when using the default installation from Veeam (which installs SQL Express in the same host as Veeam is installed). Using those default settings, SQL Authentication is disabled. It is either enabled or integrated authentication is properly configured on the database.
Following the steps outlined in the README will enable SQL authentication, create an SQL user and assign proper permissions to it. Without proper authentication and access to the database the script will be unable to get any data from the database and you will end up with an empty "JobsInfo".
Also, if you have a different setup (like hosting the database in a different server - I myself do that), you will have to adjust the script accordingly. If proper configuration on both the database and script is done, it will get the values. I am using a different setup from the default in different installations and have no issues with this.

Regards.
