### ISSUE TITLE
Return last failures in 24 hours

### ISSUE THREAD

**Issue by marcos-lazaro** [romainsi/zabbix-VB-R-SQL#33]
Hey,

It's not a problem, it's a question of whether it's possible.

I wanted to get the value of failures in the last 24 hours, for example, in the last 24 hours I had 10 failures. Would it be possible to create an item in Zabbix with that value? (10).

**Comment by aholiveira** [comment]
Hello,

Zabbix records the values of the "Last reason" and "Backup result" for far more than that (depending on your retention values).
Obviously it will only record that after it starts collecting data (it will not get past data). The template by default collects data every five minutes.
Just check the item history and you can see all of that and more.
If this is what you want/need or if it solves your question please close the issue, otherwise please describe in more detail what you need.

Regards.

**Comment by marcos-lazaro** [comment]
In fact, I need to make Zabbix take the results of the jobs (failures) and add these values, this way I can create a trigger for example: in case of 10 failures since the last collection, the trigger is activated.

Maybe it's possible to pre-process the json, adding the array with the last result, I'm not sure, I'm trying a few things.

**Comment by aholiveira** [comment]
You can use Zabbix "sum()" function on the trigger. Veeam returns 1 on Warning and 2 on error. So, if the sum is greater than 20, the last 10 results are errors. You can play around with that and maybe adjust the rate of data collection to suit your needs.
This is related to Zabbix itself, not to the template.

**Comment by marcos-lazaro** [comment]
Thanks again!

I found the expression I needed

![image](https://user-images.githubusercontent.com/123191214/214071553-297b5093-61b2-487a-9698-2239f33e7907.png)

**Comment by aholiveira** [comment]
I don't think this will yield the results you want. It returns the sum of the values received on JOBRESULT (which is a single value - the sum of which is equal to itself).
You should use "sum" on the *trigger* expression. If the sum of the last "N" values exceed a threshold you define then the trigger will fire. You can/should use macros to simplify the expression you are using and make it more readable/customizable, instead of fixing "N" and the threshold in the trigger expression. This way, you can customize those values per host/backup job.
But if this works for you, great!

**Comment by marcos-lazaro** [comment]
Really, the way I mentioned above did not work out very well, sometimes wrong data appeared. So I decided to create a new function in the script:

In my case I put an interval of 3 hours (Failures in the last 3 hours) in the DATEADD parameter.

![image](https://user-images.githubusercontent.com/123191214/214399402-432ace4d-17fb-43c7-97d0-16ab1ec596ac.png)

In zabbix just create the item "veeam.info[JobCountFail]" of type text.

**Comment by aholiveira** [comment]
Hello,
Again, I think you are using an approach which might not work out the best way.
Zabbix has tools enough to work with the unchanged template (the one currently on the repository) and get you the information you want. You have to create a trigger with the appropriate functions, but I would not try to solve this modifying the script but the triggers on the template.
The trigger functions on zabbix can check for data in the past so you just need to adjust for it to get the correct amount of data and check that, instead of doing it in the script.
The query you have on the print screen will get data from *any* job which fails, and I would suspect you want to trigger an alert when the *same* job has more than 'X' number of failures in a given time interval, which is not what you will get with that query.
Also, this issue is now closed. I'd suggest either a) reopening it or b) creating a new issue.

Regards.
